name: security-action
on: [push]

jobs:

  Install-Requeriments:
    runs-on: ubuntu-latest
    container:
      image: python:3.11.0b1-buster
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: pip install
        run: |
          python -m pip install --no-cache-dir pip==22.0.4
        
  Veracode-SAST-Pipeline-Scan:
    runs-on: ubuntu-latest
    needs: [Install-Requeriments]
    container:
      image: veracode/pipeline-scan:latest
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: scan 
        run: |
          zip -r -v pygoat.zip . -i '*.py' '*.js' '*.html'  
          java -jar /opt/veracode/pipeline-scan.jar -vid "${{ secrets.VID }}" -vkey "${{ secrets.VKEY }}" -f pygoat.zip -aid "1242124" -p "PyGoat" -jo true 
          ls -l   
        continue-on-error: true
          
      - name: save filtered results file
        uses: actions/upload-artifact@v2
        with:
          name: filtered-results
          path: filtered_results.json
        
  Veracode-SCA-Agent-Action:
    runs-on: ubuntu-latest
    needs: [Install-Requeriments]
    container:
      image: python:3.11.0b1-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: pip install
        run: |
          python -m pip install --no-cache-dir pip==22.0.4
      
      - name: Listing
        run: |
          ls -lah
      
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: | 
          export SRCCLR_SCM_URI="https://github.com/lucasferreiram3/PyGoat.git"
          export SRCCLR_SCM_REF=${{ github.workflow }}
          export SRCCLR_SCM_REF_TYPE="branch"
          export SRCCLR_SCM_REV=${{ github.run_id }}
        
          export EXTRA_ARGS='--update-advisor --uri-as-name'
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan $EXTRA_ARGS
         
        continue-on-error: true
        
  Create-Issues:
      needs: [Veracode-SAST-Pipeline-Scan, Veracode-SCA-Agent-Action]
      runs-on: ubuntu-latest
      steps:
        - name: get scan results
          uses: actions/download-artifact@v2
          with:
            name: filtered-results

        - name: import flaws as issues
          uses: buzzcode/veracode-flaws-to-issues@v1
          with:
            scan-results-json: 'filtered_results.json'
            github-token: ${{ secrets.GITHUB_TOKEN }}
   
        - name: Checkout
          uses: actions/checkout@v2
        - name: Run Veracode SCA
          env:
            SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
          uses: lerer/veracode-sca@v1.0.8

          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            quick: true
            create-issues: true 
         
      continue-on-error: true
